version: '3.4'

services:
  db:
    image: 'mariadb:10.9.3'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'codechallenge'
      MYSQL_USER: 'codechallenge'
      MYSQL_PASSWORD: 'codechallenge'
      #MYSQL_DATABASE: 'codechallenge'
    volumes:
      - "./mysql/:/var/lib/mysql"

#  phpmyadmin:
#    depends_on:
#      db:
#        condition: service_started
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 8082:80
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: 'codechallenge'
#      UPLOAD_LIMIT: 300M
  
  frontend:
    depends_on:
      app:
        condition: service_healthy
    image: nginx:latest
    restart: unless-stopped
    ports:
        - "8006:8080"
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./frontend:/app/frontend

  app:
    depends_on:
      db:
        condition: service_started
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/api/token"]
      interval: 10s
      timeout: 5s
      retries: 100
      start_period: 10s
    container_name: 'codechallenge-ddd'
    ports:
      - 8005:8005
    volumes:
        - ./app:/app
        - ./php.ini:/usr/local/etc/php/php.ini